print("hello world")
import numpy as np 
a = np.array([1,2,3])
print(a)
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape)
print(b[0,0])
print(b[0,1])
print(b[1,0])
print(b[1,1])
print(b[0,2])
print(b[1,2])
print(b[0])
print(b[1])
print(b[:,0])
print(b[:,1])
print(b[:,2])
print(b[0,:])
print(b[1,:])
print(b[:,:])
